version: '3.1'
services:
  db:
    image: postgres:12-alpine
    restart: always
    expose:
      - 5432
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
    - pgdata=/var/lib/postgresql/data

volumes:
  pgdata: